#!/usr/bin/env python3

import sys

def mm2mil(mm):
    print("%.3f mm = %u mil" % (mm, mm * 100 / 2.54))

if len(sys.argv) < 2:
    sys.exit("Usage: pcb-mm2mil <mm> [<mm>...]")

for arg in sys.argv[1:]:
    mm2mil(float(arg))
